Feat/forgot password
ltuffery/Matcha pull request #30
Opened 2024-12-05 15:28 UTC by swotex

2024-12-06 07:03 UTC, ltuffery commented on api/src/Controllers/ForgotController.php
> +            $bodyMail = str_replace('{{url}}', $url, $bodyMail);
```suggestion
            $bodyMail = str_replace(
                    ['{{username}}', '{{url}}'],
                    [htmlspecialchars($userTarget->username, ENT_QUOTES, 'UTF-8'), $url],
                    $bodyMail
            );
```
Un peu plus propre

2024-12-06 07:04 UTC, ltuffery commented on api/src/Controllers/ForgotController.php
> +            'pass2' => 'required',
C'est qui `pass1` et `pass2`, possible d'avoir des nom plus clair ?

2024-12-06 12:14 UTC, swotex commented on api/src/Controllers/ForgotController.php
> +            $bodyMail = str_replace('{{url}}', $url, $bodyMail);
Faut le modifier aussi dans email verification. c'est un peux plus propre, mais un peu moins clair non ?

2024-12-06 20:07 UTC, ltuffery commented on api/src/Controllers/ForgotController.php
> +            'pass2' => 'required',
Euh peut être mais là ça veut juste rien dire on ne sait qui correspond à quoi facilement

2024-12-08 06:50 UTC, ltuffery requested changes
N'oublie pas de faire un `npm run format`

2024-12-08 06:50 UTC, ltuffery commented on frontend/src/components/LoginForm.vue
> +          </svg>
Utilise une icon dans un fichier `.svg`

2024-12-08 06:50 UTC, ltuffery commented on frontend/src/components/LoginForm.vue
> +    <span class="">Forgot your username or password ? </br>Recive and change it by mail :</span>
`</br>` ca n'existe pas mais `<br />` oui
```suggestion
    <span>Forgot your username or password ? <br/>Recive and change it by mail :</span>
```

2024-12-08 06:50 UTC, ltuffery commented on frontend/src/views/NewPasswordView.vue
> +                </div>
Utilise un `v-else`
```suggestion
                <div v-else class="toast toast-top toast-right">
                    <div class="alert alert-error">
                    <span>{{errorContent}}</span>
                    </div>
                </div>
```

2024-12-08 06:50 UTC, ltuffery commented on frontend/src/views/NewPasswordView.vue
> +                        </svg>
Utilise un fichier `.svg`

2024-12-08 06:50 UTC, ltuffery commented on frontend/src/views/NewPasswordView.vue
> +                        </svg>
Utilise un fichier `.svg`

2024-12-08 06:50 UTC, ltuffery commented on frontend/src/components/LoginForm.vue
> +    </div>
Groupe les 2 boutons car la c'est pas tres jolie 

Exemple (du MultiStepForm.vue)
```html
<div class="flex gap-4">
    <div
        class="form-control mt-6 w-full"
        v-if="currentStep > 0"
        @click="prevStep"
    >
        <button class="btn btn-primary" type="submit">Précédent</button>
    </div>
    <div
        class="form-control mt-6 w-full"
        v-if="currentStep < props.totalSteps - 1"
        @click="nextStep"
    >
        <button class="btn btn-primary" type="submit">Suivant</button>
    </div>
</div>
```

2024-12-08 06:50 UTC, ltuffery commented on frontend/src/components/LoginForm.vue
> +        <span class="cursor-pointer hover:underline" @click="forgotSwitch">Forgot credencial ? 🥲</span>
`🥲` caractère non existant sur mon pc personnellement

2024-12-08 06:50 UTC, ltuffery commented on api/src/Controllers/ForgotController.php
> +            $mail->send();
Cela pourrais etre chouette de cree un class qui automatise un peu ceci
A méditer sur une autre PR

2024-12-09 11:56 UTC, swotex commented on frontend/src/views/NewPasswordView.vue
> +                </div>
Non, car `successed` peux avoir 3 états (true, false ou null)
True et false sonts des réponses visible, et null non.
De tout façon ce système va disparètre via la pr `feedback toast`

2024-12-09 15:36 UTC, swotex commented on frontend/src/components/LoginForm.vue
> +          </svg>
non, les classes affecte le svg (size, color, ...)

2024-12-09 15:36 UTC, swotex commented on frontend/src/views/NewPasswordView.vue
> +                        </svg>
non, les classes affecte le svg (size, color, ...)

2024-12-09 15:37 UTC, swotex commented on frontend/src/views/NewPasswordView.vue
> +                        </svg>
non, les classes affecte le svg (size, color, ...)

2024-12-09 15:37 UTC, swotex commented on api/src/Controllers/ForgotController.php
> +            $mail->send();
Je suis d'accord

2024-12-12 05:50 UTC, ltuffery approved these changes
Lgfm

2024-12-12 05:50 UTC, merged